# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59c29e5b6c98900149a43d9319436ed3d688bb6063d4041da7cd770ffafff2e9e90b741cf9450ed3831c5881f1465260c8445ce1860e7847abe6698150aeb2eb

test:
  secret_key_base: 19fcf4f398bc8be7f8a880c3164bb3f976e1720ccea106e1d546896d84ebdbd07a51bca23af03ce953543a5c305123867a0f71d7f2bb7979e7e82f9c9fd8e8ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
